### PR TITLE
User signup

### PR DESCRIPTION
**Pull request by calavell**

### CODE REVIEW

**Review by AJSMonty — COMMENTED** [review]
looks good

**Comment by chriswhitehouse** [comment]
Still need to add in encryption, but code looks good.

**Review by chriswhitehouse — COMMENTED** [review]
Looks awesome

**Comment by chriswhitehouse** [comment]
[Users can sign up (validation) [MEDIUM][SP:3]](https://trello.com/c/4qdmI9Jz/20-users-can-sign-up-validation-mediumsp3)

**Comment by chriswhitehouse** [comment]
[Users can sign up (basic) [MEDIUM][SP:4]](https://trello.com/c/kM03cZlV/7-users-can-sign-up-basic-mediumsp4)

**Pull request merged**
